apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: ${PROJECT}
  namespace: dev
spec:
  hostname: ${PROJECT}.dynacom.dev
  prefix: /
  service: ${PROJECT}.dev:80
  timeout_ms: 120000
