apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: ${PROJECT}
  namespace: ${AIS_NAMESPACE}
spec:
  hostname: ${AIS_PUBLIC_HOSTNAME}
  prefix: /
  service: ${PROJECT}.${AIS_NAMESPACE}:80
  timeout_ms: 120000
